export interface Iuser{
    name:string,
    surname:string,
    email:string,
    phone?:string,
    age:number,
    work?:string,
    hobby?:string
}

export const data:Iuser[] = [
    {
        name:"Vladimir",
        surname:"Grab",
        email:"volo@yandex.ru",
        phone:"8908869404",
        age:27,
        work:"programmer",
        hobby:"programmer"
    },
    {
        name:"Marina",
        surname:"Grab",
        email:"marina@yandex.ru",
        phone:"89088451235",
        age:30,
        work:"homeWork",
        hobby:"children"
    },
    {
        name:"Germin",
        surname:"Usupov",
        email:"usupov@yandex.ru",
        phone:"",
        age:33,
        work:"president",
        hobby:"sports"
    }
]